app = "stt-ia"
kill_signal = "SIGINT"
primary_region = "sjc"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 5_000
min_machines_running = 0
processes = [ "app" ]

[[services]]
internal_port = 5_000
protocol = "tcp"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256"